<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>TimeTracker.Infrastructure</AssemblyName>
    <RootNamespace>TimeTracker.Infrastructure</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\TimeTracker.Application\TimeTracker.Application.csproj" />
  </ItemGroup>
</Project>
