<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>TimeTracker.Application</AssemblyName>
    <RootNamespace>TimeTracker.Application</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\TimeTracker.Domain\TimeTracker.Domain.csproj" />
  </ItemGroup>
</Project>
