name: Classic Windows build

on:
  push:
  pull_request:

jobs:
  test-and-build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test
        shell: powershell
        run: .\test-classic.ps1
      - name: Build minute version
        shell: powershell
        run: .\build-classic.ps1
      - name: Build test version
        shell: powershell
        run: .\build-classic.ps1 -Test
      - uses: actions/upload-artifact@v4
        with:
          name: TimeTracker-classic
          path: artifacts/classic/*.exe
